name: 'Run Behave Tests'
description: 'A Github action to run Behave Behavioral Driven Development (BDD) tests for Python and generate test results'
author: 'cryptic-wizard'
branding:
  icon: check-square
  color: green

inputs:
  #python-version: TODO when composite action supports 'uses'
    #description: "See [actions/python-versions](https://github.com/actions/python-versions/blob/main/versions-manifest.json) for supported versions"
    #required: true
    #default: 3.10.5
  requirements-name:
    description: "Name of dependencies file (example: requirements.txt or example_project/requirements.txt or src/example_project/requirements.txt)"
    required: false
    default: 'requirements.txt'
  test-path:
    description: "Path of the features parent folder if not in root (example: example_project (if example_project/features) or src/example_project/tests (if src/example_project/tests/features))"
    required: false
    default: 'null'
  test-output-name:
    description: "Name of the output file (example: results.txt or plain.output)"
    required: false
    default: results.txt
  upload-artifact:
    description: "Set to false to disable uploading artifact automatically"
    required: false
    default: true

runs:
  using: composite
  steps:
    #- name: Checkout TODO when composite action supports 'uses'
      #uses: actions/checkout@v3
    #- name: Install Python TODO when composite action supports 'uses'
      #uses: actions/setup-python@v4
      #with:
        #python-version: ${{ inputs.python-version }}
    - name: Install Project Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f ${{ inputs.requirements-name }} ]; then
          pip install -r ${{ inputs.requirements-name }}
        else
          echo 'Requirements file ' ${{ inputs.requirements-name }} ' not found'
        fi
    - name: Run Behave Tests
      shell: bash
      id: run-behave-tests
      run: |
        pip install behave

        args=()
        ARTIFACT_FULL_PATH=${{ inputs.test-output-name }}
        echo "Artifact full path = $ARTIFACT_FULL_PATH"
        [ "${{ inputs.test-path }}" != 'null' ] && cd ${{ inputs.test-path }} && ARTIFACT_FULL_PATH=${{ inputs.test-path }}/${{ inputs.test-output-name }}
        args+=("-o" "${{ inputs.test-output-name }}")
        echo "Artifact full path = $ARTIFACT_FULL_PATH"
        echo ::set-output name=ARTIFACT_FULL_PATH::$ARTIFACT_FULL_PATH

        behave "${args[@]}"
    - name: Publish Behave Test Results
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: 'Behave Test Results'
        variables: 
        path: ${{ steps.run-behave-tests.outputs.ARTIFACT_FULL_PATH }}