name: 'Run Behave Tests'
description: 'A Github action to run Behave Behavioral Driven Development (BDD) tests for Python and generate test results'
author: 'cryptic-wizard'
branding:
  icon: check-square
  color: green

inputs:
  #python-version: TODO when composite action supports 'uses'
    #description: "See [actions/python-versions](https://github.com/actions/python-versions/blob/main/versions-manifest.json) for supported versions"
    #required: true
    #default: 3.10.5
  requirements-name:
    description: "Name of dependencies file (example: requirements.txt or example_project/requirements.txt or src/example_project/requirements.txt)"
    required: false
    default: 'requirements.txt'
  test-path:
    description: "Path of the features parent folder if not in root (example: example_project (if example_project/features) or src/example_project/tests (if src/example_project/tests/features))"
    required: false
    default: ''
  test-output-name:
    description: "Name of the output file (example: results.txt or plain.output)"
    required: false
    default: 'results.txt'
  upload-artifact:
    description: "Set to false to disable uploading artifact automatically"
    required: false
    default: true

runs:
  using: composite
  steps:
    #- name: Checkout TODO when composite action supports 'uses'
      #uses: actions/checkout@v4
    #- name: Install Python TODO when composite action supports 'uses'
      #uses: actions/setup-python@v5
      #with:
        #python-version: ${{ inputs.python-version }}
    - name: Install Project Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip -q
        if [ -f ${{ inputs.requirements-name }} ]; then
          pip install -r ${{ inputs.requirements-name }}
        else
          echo 'Requirements file ${{ inputs.requirements-name }} not found'
        fi
    - name: Run Behave Tests
      shell: bash
      id: run-behave-tests
      run: |
        pip install behave -q
        TEST_OUTPUT_NAME=${{ inputs.test-output-name }}
        BEHAVE_ARTIFACT_FULL_PATH=${{ inputs.test-output-name }}
        [ "${{ inputs.test-path }}" != '' ] && BEHAVE_ARTIFACT_FULL_PATH=${{ inputs.test-path }}/${{ inputs.test-output-name }} && cd ${{ inputs.test-path }} 

        args=()
        args+=("-o" "${{ inputs.test-output-name }}")
        echo "Behave artifact output name = $TEST_OUTPUT_NAME"
        echo "Behave artifact full path = $BEHAVE_ARTIFACT_FULL_PATH"
        echo "BEHAVE_ARTIFACT_FULL_PATH=$BEHAVE_ARTIFACT_FULL_PATH" >> $GITHUB_OUTPUT
        behave "${args[@]}"
    - name: Publish Behave Test Results
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-behave-tests.outputs.TEST_OUTPUT_NAME }}
        path: ${{ steps.run-behave-tests.outputs.BEHAVE_ARTIFACT_FULL_PATH }}