name: Python Version Complex Matrix
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10.5']
        exclude:
          - os: ubuntu-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.10.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Behave Tests
        uses: ./
        with:
          requirements-name: example_project/requirements.txt
          test-path: example_project
          test-output-name: ${{ matrix.os }}-${{ matrix.python-version }}.txt