name: Python 3.10.5 Minimal
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - name: Run Behave Tests
        uses: ./
        with:
          requirements-name: example_project/requirements.txt
          test-path: example_project